[I 11:52:34.974 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 11:52:36.210 NotebookApp] Serving notebooks from local directory: /home/pc-17741/Escritorio/API Source of Data
[I 11:52:36.210 NotebookApp] The Jupyter Notebook is running at:
[I 11:52:36.210 NotebookApp] http://(1pc7-220-17741 or 127.0.0.1):8888/
[I 11:52:36.210 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 11:52:36.211 NotebookApp] No web browser found: could not locate runnable browser.
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.16.128.11 - - [25/Apr/2019 11:53:48] "GET / HTTP/1.1" 404 -
172.16.128.11 - - [25/Apr/2019 11:53:48] "GET /favicon.ico HTTP/1.1" 404 -
172.16.128.11 - - [25/Apr/2019 11:53:54] "GET / HTTP/1.1" 404 -
[2019-04-25 11:58:50,595] ERROR in app: Exception on /pqr/2018 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 18, in get
    return self.__getData()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 34, in __getData
    data = self.__execute_query()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 49, in __execute_query
    oracleConnection = OracleConnection()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/config/oracle_connection.py", line 14, in __init__
    credentials["oracle_credentials"]["SID"])
cx_Oracle.DatabaseError: ORA-28000: la cuenta esta bloqueada
172.16.128.11 - - [25/Apr/2019 11:58:50] "GET /pqr/2018 HTTP/1.1" 500 -
[2019-04-25 12:00:51,759] ERROR in app: Exception on /pqr/2018 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 18, in get
    return self.__getData()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 34, in __getData
    data = self.__execute_query()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 49, in __execute_query
    oracleConnection = OracleConnection()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/config/oracle_connection.py", line 14, in __init__
    credentials["oracle_credentials"]["SID"])
cx_Oracle.DatabaseError: ORA-28000: la cuenta esta bloqueada
172.16.128.11 - - [25/Apr/2019 12:00:51] "GET /pqr/2018 HTTP/1.1" 500 -
[I 12:21:04.798 NotebookApp] 302 GET / (172.16.128.11) 1.29ms
[W 12:21:04.816 NotebookApp] Clearing invalid/expired login cookie username-172-16-44-9-8888
[W 12:21:04.818 NotebookApp] Clearing invalid/expired login cookie username-172-16-44-9-8888
[I 12:21:04.819 NotebookApp] 302 GET /tree? (172.16.128.11) 4.15ms
[I 12:21:08.062 NotebookApp] 302 POST /login?next=%2Ftree%3F (172.16.128.11) 2.34ms
[I 12:25:01.187 NotebookApp] Saving file at /concret_sources/config/configuration.json
[I 12:33:43.243 NotebookApp] Saving file at /concret_sources/config/configuration.json
[2019-04-25 12:33:56,318] ERROR in app: Exception on /pqr/2018 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 18, in get
    return self.__getData()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 34, in __getData
    data = self.__execute_query()
  File "/home/pc-17741/Escritorio/API Source of Data/concret_sources/pqrs_resource.py", line 53, in __execute_query
    cursor.execute(self.__query, ANIO_ARG = self.__ANIO_ARG, PERIODO_ARG = self.__PERIODO_ARG, SERVICIO_ARG = self.__SERVICIO_ARG)
cx_Oracle.DatabaseError: ORA-00942: la tabla o vista no existe
172.16.128.11 - - [25/Apr/2019 12:33:56] "GET /pqr/2018 HTTP/1.1" 500 -
[I 12:40:28.877 NotebookApp] 302 GET / (172.16.128.11) 0.92ms
[I 12:40:29.938 NotebookApp] 302 GET / (172.16.128.11) 0.84ms
[I 12:41:17.119 NotebookApp] 302 POST /login?next=%2F (172.16.128.11) 2.35ms
[I 12:41:17.127 NotebookApp] 302 GET / (172.16.128.11) 0.86ms
[I 11:12:14.832 NotebookApp] 302 GET / (172.16.128.11) 0.87ms
[I 11:12:16.112 NotebookApp] 302 GET / (172.16.128.11) 0.90ms
[C 11:17:05.867 NotebookApp] received signal 15, stopping
[I 11:17:05.868 NotebookApp] Shutting down 0 kernels
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.16.128.11 - - [09/May/2019 10:45:35] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.11 - - [09/May/2019 10:45:48] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.128.11 - - [09/May/2019 10:54:33] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:05:42] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:06:50] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:24:10] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:25:13] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:25:21] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:25:44] "GET /pqr/gas/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:25:48] "GET /pqr/glp/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:26:00] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:29:15] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:29:26] "GET /pqr/glp/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:29:33] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:47:16] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:47:35] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.33 - - [09/May/2019 11:53:15] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.11 - - [09/May/2019 12:24:47] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.128.11 - - [09/May/2019 14:21:35] "GET / HTTP/1.1" 404 -
172.16.128.11 - - [09/May/2019 15:18:59] "GET / HTTP/1.1" 404 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.16.128.11 - - [10/May/2019 09:11:25] "GET /pqr/2018 HTTP/1.1" 200 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5050/ (Press CTRL+C to quit)
172.16.128.145 - - [31/Jul/2019 16:35:54] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.44.39 - - [31/Jul/2019 16:36:22] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.44.39 - - [31/Jul/2019 16:37:10] "GET /pqr/energia/2018 HTTP/1.1" 200 -
172.16.44.39 - - [31/Jul/2019 16:37:18] "GET /pqr/gas/2018 HTTP/1.1" 200 -
172.16.44.39 - - [31/Jul/2019 16:37:22] "GET /pqr/glp/2018 HTTP/1.1" 200 -
172.16.3.42 - - [01/Aug/2019 06:12:47] "GET /pqr/2018 HTTP/1.1" 200 -
172.16.3.42 - - [01/Aug/2019 06:13:19] "GET /pqr/energia/2018 HTTP/1.1" 200 -
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    app.run(host='0.0.0.0', port=5050)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    app.run(host='0.0.0.0', port=5050)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5055/ (Press CTRL+C to quit)
